-- AlterTable
ALTER TABLE "Collection" ADD COLUMN     "hechas" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "porRevisar" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sinHacer" INTEGER NOT NULL DEFAULT 0;
